spring:
  datasource:
    url: jdbc:h2:file:./database
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



app:
  timeanalysistool:
    jwtSecret: adiSrcretKey
    jwtExpirationMs: 86400000


